import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Experience", description: "Drish Dedhia's engineering team work, internship, scholarship, and volunteering." };

export default function Experience() {
  return <>
    <header className="page-header"><div className="page-wrap inner-header"><p className="eyebrow">Experience / people and places</p><h1 className="display">Learning with <em>other people.</em></h1><p className="story-lead">A team can spot the flaw in an idea faster than I can alone. These are the people and places that have helped me ask sharper questions, explain myself better, and turn curiosity into useful work.</p></div></header>
    <section id="ecogenium" className="page-wrap experience-feature"><div data-reveal><p className="eyebrow">Current / chassis design and production</p><h2>Ecogenium, <em>RWTH Aachen.</em></h2><p>I am part of Ecogenium&apos;s chassis department, helping develop a hydrogen fuel cell vehicle for the Shell Eco-marathon. I fabricate composite chassis components, prepare tooling, and work through production issues with iterative testing. This is where a neat model meets material behaviour, deadlines, and the people who have to build it.</p><p>I am still learning, and I write down the questions, mistakes, and small breakthroughs as they happen. My Substack, <em>Logbook of a Learning Engineer</em>, is the more personal version of that journey.</p><div className="inline-actions"><a className="button-primary" href="https://drishdedhia23.substack.com/" target="_blank" rel="noopener noreferrer">Read the logbook ↗</a><a className="text-link" href="https://ecogenium.com/" target="_blank" rel="noopener noreferrer">Meet Ecogenium ↗</a></div></div><figure data-reveal><Image src="/images/experience/ecogenium-workshop.jpeg" alt="Workshop sample showing a composite chassis material and taped edges" width={1200} height={900} priority className="w-full object-cover"/><figcaption>A material sample from my Ecogenium workshop folder.</figcaption></figure></section>
    <section id="student-assistant" className="experience-archive"><div className="page-wrap"><div className="archive-intro"><p className="eyebrow">Current / student research assistant · since October 2026</p><h2 className="narrative-title">Seeing what&apos;s <em>inside.</em></h2></div><div className="archive-list"><article className="archive-row"><div className="technical">WZL | IQS / RWTH AACHEN</div><div><h3>Industrial X-ray computed tomography</h3><p>At the Chair of Intelligence in Quality Sensing, I support research on industrial CT: a way to inspect the inside and outside of technical components without taking them apart. I help prepare and perform measurements, reconstruct and analyse 3D volume data, and evaluate component quality. I also contribute to technical reports and research aimed at improving the measurement process.</p><p>What draws me to it is the link between a physical component and the data that can reveal a flaw you would otherwise miss.</p><a href="https://www.wzl.rwth-aachen.de/" target="_blank" rel="noopener noreferrer" className="text-link">About WZL at RWTH Aachen ↗</a></div></article></div></div></section>
    <section className="experience-archive"><div className="page-wrap"><div className="archive-intro"><p className="eyebrow">Earlier engineering work</p><h2 className="narrative-title">From concept to <em>critique.</em></h2></div><div className="archive-list">
      <article className="archive-row"><div className="technical">2023 / VIRTUAL INTERNSHIP</div><div><h3>STAR Space Technology and Aeronautical Rocketry</h3><p>In a five-person team, I helped visualize a static motor test pad in Fusion 360 and contributed to a proposal, blueprint work, and a Proteus electronics model. Seeing the idea become something we could point to was exciting. Some profiles overlapped, though, and the model was not fabrication-ready. That taught me to ask for critique sooner and to be clear about where a concept ends and an engineered part begins.</p><p>The founder and director, Sunny Kabrawala, later wrote me a recommendation recognizing my problem solving and teamwork.</p><Link href="/projects/star-test-pad" className="text-link">See the model and its limits ↗</Link></div></article>
      <article className="archive-row"><div className="technical">2024 / ONLINE SIMULATION</div><div><h3>GE Aerospace Explore Engineering</h3><p>I completed a Forage job simulation built around sustainable aviation fuel choices and turbofan performance. It gave me a structured way to think about technical trade-offs and how to explain a decision clearly.</p><p>This was an independent online simulation, rather than an employment placement.</p></div></article>
    </div></div></section>
    <section className="page-wrap community-section"><div className="archive-intro"><p className="eyebrow">Scholarship, service, leadership</p><h2 className="narrative-title">Good work depends on <em>people.</em></h2></div><div className="archive-list">
      <article className="archive-row"><div className="technical">2024 / FULL SCHOLARSHIP</div><div><h3>Goethe-Institut PASCH youth course</h3><p>Selected for a fully funded three-week German language and cultural course in Sankt Peter-Ording. Learning and presenting with students from different countries made German something I could use in real conversations, not just in an exam. I completed the course&apos;s A2 assessment with 91/100.</p><a href="https://www.linkedin.com/posts/drish-dedhia-2564122b1_goetheinstitut-pasch-jugendkurse-activity-7344034199768555521-vbn-" target="_blank" rel="noopener noreferrer" className="text-link">My story and photos from Germany ↗</a></div></article>
      <article className="archive-row"><div className="technical">2023–2025 / VOLUNTEERING</div><div><h3>Teaching with CRY</h3><p>I taught mathematics and English to more than 40 fourth- and fifth-grade students. Adapting a lesson to the person in front of me taught me to listen first, explain simply, and change approach when something did not land.</p></div></article>
      <article className="archive-row"><div className="technical">2024 / COMMUNITY ACTION</div><div><h3>Tree planting with Goethe and Skrap</h3><p>I joined a tree-planting initiative with Goethe-Institut and Skrap. It was a small, practical contribution, and a reminder that sustainability becomes meaningful when people make time to act on it together.</p></div></article>
      <article className="archive-row archive-row-with-image"><div className="technical">SCHOOL YEARS / EVENT LEADERSHIP</div><div><h3>Garodia Model United Nations</h3><p>As Head of Delegate Affairs on the organizing committee, I helped support delegates and keep a busy student event running. That role taught me to communicate clearly, handle competing needs calmly, and make the experience work for the people taking part.</p></div><figure><Image src="/images/experience/garodia-mun.jpg" alt="Garodia Model United Nations organizing team on stage" width={720} height={480} className="w-full object-cover"/></figure></article>
    </div></section>
  </>;
}
