import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Experience", description: "Drish Dedhia's engineering team work, internship, scholarship, and volunteering." };

export default function Experience() {
  return <>
    <header className="border-b border-[#35515b] bg-[#142832] py-20"><div className="page-wrap"><p className="eyebrow">Experience / 01</p><h1 className="display mt-4 text-5xl font-extrabold sm:text-7xl">Learning with other people.</h1><p className="story-lead mt-6 max-w-3xl text-lg">The most useful lessons have come from teams, mentors, and people with a different view of the same problem. Here is where I have put my curiosity to work.</p></div></header>
    <section id="ecogenium" className="page-wrap story-section grid items-center gap-10 lg:grid-cols-[1fr_.9fr]">
      <div><p className="eyebrow">Current / student engineering team</p><h2 className="display mt-3 text-4xl font-extrabold">Ecogenium, RWTH Aachen</h2><p className="story-lead mt-5">I am part of the chassis department of Ecogenium, a student team developing a hydrogen fuel cell vehicle for the Shell Eco-marathon. The work is giving me a closer view of how material choices, geometry, fabrication, and team communication meet in a real vehicle program.</p><p className="story-lead mt-3">I am still early in this chapter, so I document the questions and mistakes alongside progress. My Substack, <em>Logbook of a Learning Engineer</em>, is the more personal account of that learning.</p><div className="mt-7 flex flex-wrap gap-3"><a className="button-primary" href="https://drishdedhia23.substack.com/" target="_blank" rel="noopener noreferrer">Read the Ecogenium logbook &rarr;</a><a className="button-secondary" href="https://ecogenium.com/" target="_blank" rel="noopener noreferrer">Meet Ecogenium &rarr;</a></div></div>
      <figure className="story-card overflow-hidden"><Image src="/images/experience/ecogenium-workshop.jpeg" alt="Workshop sample showing a composite chassis material and taped edges" width={1200} height={900} priority className="aspect-[4/3] w-full object-cover"/><figcaption className="p-4 text-sm text-[#c0cfca]">A material sample from my Ecogenium workshop folder.</figcaption></figure>
    </section>
    <section className="border-y border-[#35515b] bg-[#142832]"><div className="page-wrap story-section"><p className="eyebrow">Early engineering experience</p><h2 className="display mt-3 text-4xl font-extrabold">From concept to critique.</h2><div className="mt-8 grid gap-5 lg:grid-cols-2">
      <article className="story-card p-7"><p className="technical text-[11px] text-[#f4b58d]">2023 / VIRTUAL MECHANICAL DESIGN INTERNSHIP</p><h3 className="display mt-3 text-2xl font-extrabold">STAR Space Technology and Aeronautical Rocketry</h3><p className="story-lead mt-4">In a five-person team, I helped visualize a static motor test pad in Fusion 360 and contributed to a proposal, blueprint work, and a Proteus electronics model. The design gave the team a shared picture of the idea, but some profiles overlapped. I learned to separate a useful concept model from a fabrication-ready one, and to seek technical critique earlier.</p><p className="mt-4 text-sm leading-7 text-[#c0cfca]">The founder and director, Sunny Kabrawala, later wrote me a recommendation recognizing my problem solving and teamwork.</p><Link href="/projects/star-test-pad" className="mt-5 inline-block font-bold text-[#f4b58d] hover:underline">See the model and its limitations &rarr;</Link></article>
      <article className="story-card p-7"><p className="technical text-[11px] text-[#f4b58d]">2024 / ONLINE JOB SIMULATION</p><h3 className="display mt-3 text-2xl font-extrabold">GE Aerospace Explore Engineering</h3><p className="story-lead mt-4">I completed a Forage job simulation built around sustainable aviation fuel choices and turbofan performance. It gave me a structured way to think about trade-offs in aviation engineering and how an engineering decision needs both technical context and a clear explanation.</p><p className="mt-4 text-sm leading-7 text-[#c0cfca]">This was an independent online simulation, rather than an employment placement.</p></article>
    </div></div></section>
    <section className="page-wrap story-section"><p className="eyebrow">Scholarship & service</p><h2 className="display mt-3 text-4xl font-extrabold">Engineering is also communication.</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">
      <article className="story-card p-7"><p className="technical text-[11px] text-[#f4b58d]">2024 / FULL SCHOLARSHIP</p><h3 className="display mt-3 text-2xl font-extrabold">Goethe-Institut PASCH youth course</h3><p className="story-lead mt-4">Selected for a fully funded three-week German language and cultural course in Sankt Peter-Ording, Germany. Learning and presenting with students from different countries made German something I could use in real conversations, not just in an exam. I completed the course&apos;s A2 assessment with 91/100.</p><a href="https://www.linkedin.com/posts/drish-dedhia-2564122b1_goetheinstitut-pasch-jugendkurse-activity-7344034199768555521-vbn-" target="_blank" rel="noopener noreferrer" className="mt-5 inline-block font-bold text-[#f4b58d] hover:underline">My story and photos from Germany &rarr;</a></article>
      <article className="story-card p-7"><p className="technical text-[11px] text-[#f4b58d]">2023–2025 / VOLUNTEERING</p><h3 className="display mt-3 text-2xl font-extrabold">Teaching with CRY</h3><p className="story-lead mt-4">I taught mathematics and English to more than 40 fourth- and fifth-grade students through CRY. Adapting a lesson to the person in front of me taught me to listen first, explain simply, and change approach when something did not land.</p></article>
      <article className="story-card p-7"><p className="technical text-[11px] text-[#f4b58d]">2024 / COMMUNITY ACTION</p><h3 className="display mt-3 text-2xl font-extrabold">Tree planting with Goethe and Skrap</h3><p className="story-lead mt-4">I joined a tree-planting initiative with Goethe-Institut and Skrap. It was a small, practical contribution, and a reminder that sustainability becomes meaningful when people make time to act on it together.</p></article>
    </div>
    <article className="story-card mt-5 grid overflow-hidden md:grid-cols-[1fr_.65fr]"><div className="p-7"><p className="technical text-[11px] text-[#f4b58d]">SCHOOL YEARS / EVENT LEADERSHIP</p><h3 className="display mt-3 text-2xl font-extrabold">Garodia Model United Nations</h3><p className="story-lead mt-4">As Head of Delegate Affairs on the organizing committee, I helped support the delegates and keep a busy student event running. That role taught me to communicate clearly, handle competing needs calmly, and make the experience work for the people taking part.</p></div><figure className="relative min-h-64"><Image src="/images/experience/garodia-mun.jpg" alt="Garodia Model United Nations organizing team on stage" fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover"/></figure></article>
    </section>
  </>;
}
