import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getChildhoodProjects } from "@/lib/projects";

export const metadata: Metadata = { title: "More about me", description: "Drish Dedhia's education, interests, languages, and path into mechanical engineering." };

const languages = [["German", "C1-level professional working proficiency · TestDaF TDN 4 in all four sections"], ["English", "Fluent / academic and professional"], ["Kutchi", "Mother tongue"], ["Hindi", "Fluent"], ["Gujarati", "Fluent"], ["Marathi", "B1 / intermediate"]];

export default function About() {
  const childhood = getChildhoodProjects();
  return <>
    <header className="about-header"><div className="page-wrap about-header-layout"><div><p className="eyebrow">About / from Mumbai to Aachen</p><h1 className="display">Curiosity came <em>first.</em></h1><p className="story-lead">Before I knew the word “engineering,” I wanted to see what made toy cars move and why old appliances worked. I still follow the same instinct; I just have better questions and better tools now.</p></div><figure><div className="formal-portrait"><Image src="/images/about/drish-formal.jpg" alt="Drish Dedhia facing the camera and smiling in a blazer" fill priority sizes="(max-width: 800px) 90vw, 420px" /></div><figcaption>Hi, I&apos;m Drish! I&apos;m really glad you&apos;re here.</figcaption></figure></div></header>
    <section className="page-wrap about-story"><div><p className="eyebrow">The path here</p><h2 className="narrative-title">From taking things apart to <em>designing them.</em></h2></div><div><p>As a child, I wanted to know what was inside a machine almost as much as I wanted to use it. I made little things from whatever I could find, then gradually learned to ask better questions of each build: What should it do? Why this shape? What might make it fail?</p><p>At Garodia International Centre for Learning, physics, mathematics, and economics gave that curiosity some structure. I completed the International Baccalaureate with 44 out of 45 points and graduated as class valedictorian. Now I study mechanical engineering at RWTH Aachen, where building a student vehicle with Ecogenium and researching industrial CT at WZL | IQS give me new reasons to test what I think I know.</p><p>Automotive systems and renewable energy particularly excite me, though I want to stay open to the problems I have not met yet. I hope to become an engineer who can take an idea from a sound model toward a practical part, explain the trade-offs clearly, and learn as much from the people building beside me as from the tools on my screen.</p></div></section>
    <section className="about-numbers"><div className="page-wrap"><p className="eyebrow">A few numbers, with context</p><div className="about-stat-list"><div><strong>44/45</strong><span>International Baccalaureate result</span></div><div><strong>100%</strong><span>Funded Goethe-Institut youth course scholarship</span></div><div><strong>40+</strong><span>Students taught through CRY volunteering</span></div><div><strong>4</strong><span>Areas explored through written research</span></div></div></div></section>
    <section className="about-details"><div className="page-wrap about-details-layout"><div><p className="eyebrow">Education</p><h2>Learning across <em>disciplines.</em></h2><div className="about-school"><strong>RWTH Aachen University</strong><span>B.Sc. Mechanical Engineering · 2025–present</span><strong>Garodia International Centre for Learning</strong><span>International Baccalaureate · Physics HL, Mathematics AA HL, Economics HL</span><p>I received a 50% tuition scholarship for the IB program and was named International Student of the Year.</p></div><p>Beyond coursework, I served as Agni House Captain and helped start a Financial Literacy Club. Both taught me that good ideas depend on bringing people along with you.</p></div><div><p className="eyebrow">Languages</p><h2>Working across <em>cultures.</em></h2><div className="about-languages">{languages.map(([language, level]) => <div key={language}><strong>{language}</strong><span>{level}</span></div>)}</div><p>The Goethe PASCH scholarship gave me my first real chance to live in German instead of only studying it. I came home more willing to start a conversation, make a mistake, and learn from it.</p></div></div></section>
    {childhood.length > 0 && <section id="the-beginning" className="page-wrap about-beginning"><div><p className="eyebrow">The first builds</p><h2 className="narrative-title">The curiosity has a <em>history.</em></h2></div><div className="about-childhood-list">{childhood.map(project => <Link key={project.slug} href={`/projects/${project.slug}`}><strong>{project.title}</strong><span>{project.shortDescription}</span><span aria-hidden="true">↗</span></Link>)}</div></section>}
  </>;
}
