import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getChildhoodProjects } from "@/lib/projects";

export const metadata: Metadata = { title: "More about me", description: "Drish Dedhia's education, interests, languages, and path into mechanical engineering." };

export default function About() {
  const childhood = getChildhoodProjects();
  return <>
    <header className="hero-ambient border-b border-[#35515b]"><div className="page-wrap grid items-center gap-12 py-16 lg:grid-cols-[1fr_.85fr] lg:py-24"><div><p className="eyebrow">More about me / 05</p><h1 className="display mt-4 text-5xl font-extrabold leading-tight sm:text-7xl">Curiosity came first.</h1><p className="story-lead mt-6 max-w-xl text-lg">Before I knew the word “engineering,” I wanted to see what made toy cars move and why old appliances worked. I still follow the same instinct; I just have better questions and better tools now.</p></div><figure className="mx-auto w-full max-w-[430px]"><div className="formal-portrait w-full border-4 border-[#d08b68] shadow-[0_28px_90px_rgba(0,0,0,.35)]"><Image src="/images/about/drish-formal.jpg" alt="Drish Dedhia facing the camera and smiling in a blazer" fill priority sizes="(max-width: 1024px) 90vw, 430px" /></div><figcaption className="mt-5 text-center text-sm text-[#c0cfca]">Hi, I’m Drish. It’s good to meet you.</figcaption></figure></div></header>
    <section className="page-wrap story-section"><div className="grid gap-10 lg:grid-cols-[.38fr_.62fr]"><div><p className="eyebrow">The path here</p><h2 className="display mt-3 text-4xl font-extrabold">From taking things apart to designing them.</h2></div><div className="space-y-5 text-lg leading-9 text-[#c0cfca]"><p>As a child, I loved the inside of a machine as much as the outside. I made small things from whatever I could find, then learned to put a question behind the build: What should it do? Why this shape? What would make it fail?</p><p>At Garodia International Centre for Learning, physics, mathematics, and economics gave that curiosity a structure. I completed the International Baccalaureate with 44 out of 45 points and graduated as class valedictorian. The path led me to RWTH Aachen, where I now study mechanical engineering and am finding my direction through design work, experiments, and a student vehicle team.</p><p>I am drawn to automotive systems and renewable energy, but I do not want to narrow the field too early. My aim is to become the kind of engineer who can move from a sound model to a practical part, explain the trade-offs honestly, and keep learning from the people building beside me.</p></div></div></section>
    <section className="border-y border-[#35515b] bg-[#142832]"><div className="page-wrap story-section"><p className="eyebrow">At a glance</p><h2 className="display mt-3 text-4xl font-extrabold">A few numbers, with context.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="story-card p-6"><p className="display text-4xl font-extrabold">44/45</p><p className="mt-2 text-sm leading-6 text-[#c0cfca]">International Baccalaureate result</p></div><div className="story-card p-6"><p className="display text-4xl font-extrabold">100%</p><p className="mt-2 text-sm leading-6 text-[#c0cfca]">Funded Goethe-Institut youth course scholarship</p></div><div className="story-card p-6"><p className="display text-4xl font-extrabold">40+</p><p className="mt-2 text-sm leading-6 text-[#c0cfca]">Students taught through CRY volunteering</p></div><div className="story-card p-6"><p className="display text-4xl font-extrabold">4</p><p className="mt-2 text-sm leading-6 text-[#c0cfca]">Areas explored through written research</p></div></div></div></section>
    <section className="page-wrap story-section grid gap-12 lg:grid-cols-2">
      <div><p className="eyebrow">Education</p><h2 className="display mt-3 text-3xl font-extrabold">Learning across disciplines.</h2><div className="mt-6 border-l-2 border-[#b75132] pl-6"><p className="font-extrabold">RWTH Aachen University</p><p className="text-sm text-[#c0cfca]">B.Sc. Mechanical Engineering · 2025–present</p><p className="mt-4 font-extrabold">Garodia International Centre for Learning</p><p className="text-sm text-[#c0cfca]">International Baccalaureate · Physics HL, Mathematics AA HL, Economics HL</p><p className="mt-3 text-sm leading-7 text-[#c0cfca]">I received a 50% tuition scholarship for the IB program and was named International Student of the Year.</p></div><p className="story-lead mt-6">Beyond coursework, I served as Agni House Captain and helped start a Financial Literacy Club. Both taught me that good ideas depend on bringing people along with you.</p></div>
      <div><p className="eyebrow">Languages</p><h2 className="display mt-3 text-3xl font-extrabold">Working across cultures.</h2><div className="mt-6 divide-y divide-[#35515b] border-y border-[#35515b]">{[["English","Fluent / academic and professional"],["Hindi","Fluent"],["Gujarati","Fluent"],["German","B2 level / Goethe language study"]].map(([language, level]) => <div key={language} className="flex justify-between gap-5 py-4"><span className="font-extrabold">{language}</span><span className="text-right text-sm text-[#c0cfca]">{level}</span></div>)}</div><p className="story-lead mt-5">The Goethe PASCH scholarship took me from classroom German to everyday conversations in Germany. It made me more willing to speak before every sentence was perfect.</p></div>
    </section>
    {childhood.length > 0 && <section id="the-beginning" className="border-t border-[#35515b] bg-[#142832]"><div className="page-wrap story-section"><p className="eyebrow">The first builds</p><h2 className="display mt-3 text-4xl font-extrabold">The curiosity has a history.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{childhood.map(project => <Link key={project.slug} href={`/projects/${project.slug}`} className="story-card p-6 hover:text-[#f4b58d]"><h3 className="display text-xl font-extrabold">{project.title}</h3><p className="mt-2 text-sm leading-7 text-[#c0cfca]">{project.shortDescription}</p><span className="mt-4 inline-block text-sm font-extrabold">Read the story &rarr;</span></Link>)}</div></div></section>}
  </>;
}
